### ISSUE TITLE
I'm using the buf tool to generate a ts file and have set `-ts_proto_opt=esModuleInterop=true`, but the generated code still contains `import Long = require("long");`

### ISSUE THREAD

**Issue by TraderWithPython** [stephenh/ts-proto#1001]
I'm using the buf tool to generate a ts file and have set `-ts_proto_opt=esModuleInterop=true`, but the generated code still contains `import Long = require("long");`

This is my buf configuration file:

```
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/community/stephenh-ts-proto
    out: .
    opt:
      - ts_proto_opt=esModuleInterop=true
      - logtostderr=true
      - allow_merge=true
      - json_names_for_fields=false
      - ts_proto_opt=snakeToCamel=true
```

thanks for helping

**Comment by stephenh** [comment]
I'm not a buf user, but I'm pretty sure the `ts_proto_opt` is implied, i.e. you should do:

```
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/community/stephenh-ts-proto
    out: .
    opt:
      - esModuleInterop=true
      - snakeToCamel=true
```

Based on the example in our readme.
