### ISSUE TITLE
Duplicate generated file name

### ISSUE THREAD

**Issue by upMKuhn** [stephenh/ts-proto#366]
Hello,

Thank you for your library! I encountered the following warning when using. http://buf.build

Import within the protobuf file leads to the warning below.
```
import "google/protobuf/any.proto";
```
```
Warning: Duplicate generated file name "google/protobuf/any.ts". Buf will continue without error here and drop the second occurrence of this file, but please raise an issue with the maintainer of the plugin.
```

**Comment by boukeversteegh** [comment]
Any results on this @upMKuhn ?

**Comment by nick-lehmann** [comment]
I can confirm that adding `strategy: all` indeed fixes the problem. See the reference [here](https://docs.buf.build/configuration/v1/buf-gen-yaml#strategy) for what it does.

**Comment by stephenh** [comment]
Great, thanks @nick-lehmann ! I've added a note about this to the readme.

Actually, could anyone post a super-minimal version of their `buf.gen.yaml` config that has `ts-proto` in it? Then we could include that snippet in the readme as well. Thanks!

**Comment by nick-lehmann** [comment]
Sure, I can give an excerpt from my current `buf.gen.yaml`:

```yaml
version: v1
plugins:
  - name: ts
    out: ../gen/ts
    strategy: all
    path: ../node_modules/ts-proto/protoc-gen-ts_proto
```
