### ISSUE TITLE
buf registry arguments

### ISSUE THREAD

**Issue by aaly00** [stephenh/ts-proto#659]
How do I pass this argument when generating using the buf registery --ts_proto_opt=outputServices=nice-grpc,outputServices=generic-definitions,useExactTypes=false

**Comment by stephenh** [comment]
I don't personally use buf looking at their docs:

https://docs.buf.build/configuration/v1/buf-gen-yaml

I'm pretty sure:

```

version: v1
plugins:
  - remote: ...
    out: ...
    opt:
      - outputServices=nice-grpc
      - useExactTypes=false
```

You're passing `outputServices` twice...I actually forget if that is supported or not.

I'll update the readme with ^ but let me know what ends up working for you, and I'll keep the readme updated. Thanks!
