### ISSUE TITLE
null Date returning 0001-01-01T00:00:00.000Z

### ISSUE THREAD

**Issue by tomspeak** [stephenh/ts-proto#841]
```typescript
export interface MyData {
  myField: Date | undefined;
}
```

I have this type definition being generated via buf.build plugins

```
version: v1
plugins:
  - plugin: buf.build/community/stephenh-ts-proto
    out: gen/ts
    opt: # https://github.com/stephenh/ts-proto#supported-options and https://github.com/stephenh/ts-proto#nestjs-support
      - env=node
      - addGrpcMetadata=true
      - nestJs=true
      - forceLong=string
      - useDate=true
```

The issue is that when my gRPC service returns a `Null` `Timestamp` for `myField`, what that is serialized to is

```typescript
myField: "0001-01-01T00:00:00.000Z"
```

**Question 1: Is this a bug as I am combining `useDate` and `forceLong=string`?**

The type definitions in the original `toObject` (`toObject(message: { seconds: number; nanos: number })`) made me wonder if some weird conversion is going on.

A hack around this is, in my NestJS controller I have added

```typescript
wrappers['.google.protobuf.Timestamp'] = {
  ...wrappers['.google.protobuf.Timestamp'],
  toObject(message: { seconds: number; nanos: number }) {
    return message && message.seconds && message.nanos
      ? new Date(message.seconds * 1000 + message.nanos / 1e6)
      : undefined;
  },
} as any;
```

This now correctly does not return `myField` as it is `undefined`, the issue is that this seems to only work if I put it directly in my controller, so I would have to keep repeating this over and over.

**Question 2: If this is the way to override this behaviour, is there a better way to do it?**

Many thanks
